services:
  db:
    image: postgres:15-alpine
    container_name: promoscout_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: promoscout
    ports:
      - "5433:5433"
    volumes:
      - promoscout_data:/var/lib/postgresql/data

volumes:
  promoscout_data: