[project]
name = "promoscout"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.13"
dependencies = [
    "accelerate>=1.10.1",
    "requests>=2.32.5",
    "torch>=2.8.0",
    "transformers>=4.57.3",
]
